import Head from "next/head";
import Header from "../components/Header";
import { useSelector } from "react-redux";
import Button from "../components/Button";
import { selectCartItems, selectCartTotal } from "../redux/cartSlice";
import { useRouter } from "next/router";
import { useState } from "react";
import { useEffect } from "react";
import CheckoutProduct from "../components/CheckoutProduct";

function Checkout() {
  const items = useSelector(selectCartItems);
  const router  = useRouter();
  const [groupItemsCart, setGroupItemsCart] = useState({});

  useEffect(() => {
  const groupItems = items.reduce((results, item) => {
    (results[item._id] = results[item._id] || []).push(item);
    return results;

  //initialValue
  }, {});
  setGroupItemsCart(groupItems);
  },[items]);
  
  return (
    <div className=''>
      <Head>
        <title>Equal E-Commerce | Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
    <main>
      <div>
        <h1 className="my-4 text-3xl font-semibold lg:text-4xl">
          {items.length > 0 ? "Review your bag." : "Your bag is empty."}
        </h1>
        <p className="my-4">Free delivery and free returns.</p>
        
        {items.length === 0 && (
          <Button 
          title="Continue Shopping"
          onClick={() => router.push("/")}
          />
        )}
      </div>
      {items.length > 0 && (
        <div className="mx-5 md:mx-8">
         {Object.entries(groupItemsCart).map(([key, items]) => (
           <CheckoutProduct key={key} items={items} id={key}/>
         ))}
        </div>
      )}
    </main>
  
    </div>
  )
}

export default Checkout;