
const checkout = () => {
  return (
    <div className=''>
      <Head>
        <title>Equal E-Commerce | Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
    <Header/>
    </div>
  )
}

export default checkout