import { Tab } from '@headlessui/react'
import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'
import LandingPage from '../components/LandingPage'


const Home = () => {
  ///console.log(categories)
  return (
    <div>
         <Head>
        <title>Equal E-Commerce | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/> 
      <main className='relative h-[200vh] bg-[#e7ecee]'>
        <LandingPage/>
      </main>

      {/*Landing Page-2 Starts From Here*/}

      <section className='relative z-50 -mt-[100vh] min-h-screen bg-[#1b1b1b]'>
        <div className='space-y-10 py-16 '>
        <h1 className='text-center text-4xl font-medium tracking-wide text-white md:text-5xl'>
       New Promos
       </h1>
       <Tab.Group>
       <Tab.List >
        <Tab>Mac</Tab>
        <Tab>iPhone</Tab>
        <Tab>iPad</Tab>
        <Tab>iWatch</Tab>  
            </Tab.List>
      <Tab.Panels>
        <Tab.Panel>Content 1</Tab.Panel>
        <Tab.Panel>Content 2</Tab.Panel>
        <Tab.Panel>Content 3</Tab.Panel>
      </Tab.Panels>
    </Tab.Group>
        </div>
      </section>
    </div>
  )
}

export default Home;