import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'
import LandingPage from '../components/LandingPage'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Equal E-Commerce | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header/>
     <main className='relative h-[200vh] bg-[#e7ecee]'>
        <LandingPage/>
        </main>

        {/* Landing Page 2 */}
        <h2>Page 2</h2>
    </div>
  )
}
